/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HS.View;

import HS.Model.Model_Phong;
import HS.Repo.Repo_Phong;
// Import Repo_Ds_Phong
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class Chi_Tiet_Phong extends javax.swing.JPanel {

    private View_Main mainForm;
    private Repo_Phong repoPhong = new Repo_Phong();

    public Chi_Tiet_Phong(String maphong, View_Main main) {
        this.mainForm = main;
        initComponents();
        String maphong1 = maphong;
        initData(maphong1);

    }
    

    public void initData(String maphong) {
        try {
            // Lấy thông tin phòng từ repo
            Model_Phong danhsach = repoPhong.getById(maphong);

            // Kiểm tra nếu không tìm thấy phòng
            if (danhsach == null) {
                System.out.println("Không tìm thấy phòng với mã: " + maphong);
                return;
            }

            // Cập nhật thông tin phòng lên giao diện
            lblMaPhong.setText(danhsach.getId_phong());

            // Kiểm tra trạng thái phòng
            if (danhsach.isTrangthai()) { // Nếu phòng đang sử dụng (trang thái = true)
                JpaneView.setBackground(Color.red);
                btn_xacnhan.setText("Thanh toán");
                btn_xacnhan.setBackground(Color.BLUE);
                
                lblTrangThai.setText(danhsach.getTrangThai());
                lblLoaiPhong.setText(danhsach.getLoaiPhong());
            } else { // Nếu phòng không sử dụng (trang thái = false)
                 JpaneView.setBackground(Color.GREEN);
                btn_xacnhan.setText("Đặt phòng");
             
                lblTrangThai.setText(danhsach.getTrangThai());
              lblLoaiPhong.setText(danhsach.getLoaiPhong());
            }
           
            

        } catch (Exception e) {
            System.out.println(e);
        }
    }
// private void handleButtonClick(java.awt.event.ActionEvent evt) {
//    String maPhong = lblMaPhong.getText();
//    Model_Phong phong = repoPhong.getById(maPhong);
//
//    if (phong.getTrangThai().equals("Đang sử dụng")) {
//        System.out.println("Thực hiện thanh toán cho phòng " + maPhong);
//        phong.setTrangthai(false); // Trả phòng (Cập nhật trạng thái về "Trống")
//    } else {
//        System.out.println("Đặt phòng " + maPhong);
//        phong.setTrangthai(true); // Đặt phòng
//    }
//
//    // Cập nhật trạng thái phòng theo giá trị thực tế
//    repoPhong.update(phong);
//
//    // Cập nhật lại giao diện sau khi thay đổi trạng thái
//    initData(maPhong);
//}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JpaneView = new javax.swing.JPanel();
        lblMaPhong = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lblLoaiPhong = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        btn_xacnhan = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        JpaneView.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMaPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaPhong.setText("Mã Phòng:");

        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl2.setText("Loại phòng:");

        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl3.setText("Trạng thái: ");

        lblLoaiPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLoaiPhong.setText("Loại phòng:");

        lblTrangThai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTrangThai.setText("Trạng thái: ");

        btn_xacnhan.setText("Đặt phòng");
        btn_xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacnhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpaneViewLayout = new javax.swing.GroupLayout(JpaneView);
        JpaneView.setLayout(JpaneViewLayout);
        JpaneViewLayout.setHorizontalGroup(
            JpaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JpaneViewLayout.createSequentialGroup()
                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JpaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpaneViewLayout.createSequentialGroup()
                                .addComponent(btn_xacnhan)
                                .addGap(0, 73, Short.MAX_VALUE))
                            .addComponent(lblTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(JpaneViewLayout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLoaiPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JpaneViewLayout.setVerticalGroup(
            JpaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaPhong)
                .addGap(18, 18, 18)
                .addGroup(JpaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(lblLoaiPhong))
                .addGap(26, 26, 26)
                .addGroup(JpaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(lblTrangThai))
                .addGap(33, 33, 33)
                .addComponent(btn_xacnhan)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpaneView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpaneView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 67, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 67, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacnhanActionPerformed
        // TODO add your handling code here:
        
        String value = btn_xacnhan.getText();
        String maphong = lblMaPhong.getText();
        String loaiphong = lblLoaiPhong.getText();

// Tạo đối tượng tương ứng với trạng thái nút
        if (value.equals("Đặt phòng")) {
            // Khi nút là "Đặt phòng", mở form Phiếu Đặt
            FormPhieuDat phieudat = new FormPhieuDat(maphong, loaiphong, mainForm);
            phieudat.setVisible(true);
          
            
        } else {
            // Khi nút là "Thanh toán", mở form Thanh Toán
//            FormThanhToan hoadon = new FormThanhToan(maphong, mainForm);
  //          hoadon.setVisible(true);
        }


    }//GEN-LAST:event_btn_xacnhanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpaneView;
    private javax.swing.JButton btn_xacnhan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblLoaiPhong;
    private javax.swing.JLabel lblMaPhong;
    private javax.swing.JLabel lblTrangThai;
    // End of variables declaration//GEN-END:variables
}
