/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HS.View;

import HS.Model.Model_Phong;
import HS.Repo.Repo_Ds_Phong; 
// Import Repo_Ds_Phong
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class Chi_Tiet_Phong extends javax.swing.JPanel {
     private View_Main mainForm; // Tham chiếu của form chính
    Repo_Ds_Phong repoPhong = new Repo_Ds_Phong(); // Khởi tạo đối tượng Repo_Ds_Phong
    Model_Phong dsp=new Model_Phong();

    public Chi_Tiet_Phong(String maphong, View_Main main) {
        this.mainForm = main;
        initComponents();
         String maphong1 = maphong;
        initData(maphong1);
       // Khởi tạo dữ liệu phòng từ mã phòng
    }
 public void initData(String maphong) {
    try {
        Model_Phong danhsach = repoPhong.findById(maphong);
        
        // Kiểm tra nếu đối tượng danhsach là null
        if (danhsach == null) {
            System.out.println("Không tìm thấy phòng với mã: " + maphong);
            return;  // Dừng lại nếu không tìm thấy phòng
        }

        // Tiếp tục xử lý nếu phòng tồn tại
        lblMaPhong.setText(danhsach.getId_Phong());

        if (danhsach.getTrangThaiAsString().equals("Đang sử dụng")) {
            JpaneView.setBackground(Color.red);
            btn_xacnhanj.setText("Thanh toán");
            btn_xacnhanj.setBackground(Color.BLUE);
        } else {
            JpaneView.setBackground(Color.GREEN);
            btn_xacnhanj.setText("Đặt phòng");
             btn_xacnhanj.setBackground(Color.white);
        }

        lblKieuPhong.setText(danhsach.getGhi_Chu());
        lblLoaiPhong.setText(danhsach.getLoaiPhongAsString());
        lblTrangThai.setText(danhsach.getTrangThaiAsString());

    } catch (Exception e) {
        System.err.println("Lỗi khi tải dữ liệu phòng: " + e.getMessage());
    }
}

 
 
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JpaneView = new javax.swing.JPanel();
        lblMaPhong = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lblLoaiPhong = new javax.swing.JLabel();
        lblKieuPhong = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        btn_xacnhanj = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        JpaneView.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMaPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaPhong.setText("Mã Phòng:");

        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl1.setText("Kiểu phòng:");

        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl2.setText("Loại phòng:");

        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl3.setText("Trạng thái: ");

        lblLoaiPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLoaiPhong.setText("Loại phòng:");

        lblKieuPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKieuPhong.setText("Kiểu phòng:");

        lblTrangThai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTrangThai.setText("Trạng thái: ");

        btn_xacnhanj.setText("Đặt phòng");
        btn_xacnhanj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacnhanjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpaneViewLayout = new javax.swing.GroupLayout(JpaneView);
        JpaneView.setLayout(JpaneViewLayout);
        JpaneViewLayout.setHorizontalGroup(
            JpaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JpaneViewLayout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKieuPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                    .addGroup(JpaneViewLayout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLoaiPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JpaneViewLayout.createSequentialGroup()
                        .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JpaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpaneViewLayout.createSequentialGroup()
                                .addComponent(btn_xacnhanj)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        JpaneViewLayout.setVerticalGroup(
            JpaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpaneViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaPhong)
                .addGap(18, 18, 18)
                .addGroup(JpaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(lblKieuPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2)
                    .addComponent(lblLoaiPhong))
                .addGap(12, 12, 12)
                .addGroup(JpaneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(lblTrangThai))
                .addGap(18, 18, 18)
                .addComponent(btn_xacnhanj)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpaneView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpaneView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 67, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 67, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xacnhanjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacnhanjActionPerformed
        // TODO add your handling code here:
         
         String value = btn_xacnhanj.getText();
    
    // Lấy thông tin từ các JLabel
    String maPhong = lblMaPhong.getText(); // Mã phòng
    String loaiPhong = lblLoaiPhong.getText(); // Loại phòng

    // Tạo đối tượng FormPhieuDat hoặc FormThanhToan tùy theo trạng thái nút
   
      Phieu_dat phieuDat = new Phieu_dat(maPhong, loaiPhong, mainForm);
phieuDat.setVisible(true);

    }//GEN-LAST:event_btn_xacnhanjActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpaneView;
    private javax.swing.JButton btn_xacnhanj;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblKieuPhong;
    private javax.swing.JLabel lblLoaiPhong;
    private javax.swing.JLabel lblMaPhong;
    private javax.swing.JLabel lblTrangThai;
    // End of variables declaration//GEN-END:variables
}
