/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HS.View;

import HS.Model.Model_DichVu;
import HS.Model.Model_Phong;
import HS.Repo.Repo_Phong;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quyet
 */
public class Phong1_View extends javax.swing.JFrame {

    private Repo_Phong repo = new Repo_Phong();
    private DefaultTableModel mol = new DefaultTableModel();
    private int index = -1;

    public Phong1_View() {
        initComponents();
        this.fillTable(repo.getAll());
        index = repo.getAll().size();
        this.showData(index - 1);
    }

    private void fillTable(ArrayList<Model_Phong> list) {

        mol = (DefaultTableModel) tbl_bang.getModel();

        mol.setRowCount(0);
        for (Model_Phong x : list) {
            mol.addRow(x.toDataRow());
        }
    }

final void showData(int index) {
    try {
        if (index < 0 || index >= tbl_bang.getRowCount()) {
            JOptionPane.showMessageDialog(this, "Vi tri khong hop le");
            return;
        }

        txt_id_Phong.setText(tbl_bang.getValueAt(index, 0) != null ? tbl_bang.getValueAt(index, 0).toString() : "");
        txt_gia_Phong.setText(tbl_bang.getValueAt(index, 1) != null ? tbl_bang.getValueAt(index, 1).toString() : "");

        String trangThai = tbl_bang.getValueAt(index, 2) != null ? tbl_bang.getValueAt(index, 2).toString() : "";
        String loaiPhong = tbl_bang.getValueAt(index, 3) != null ? tbl_bang.getValueAt(index, 3).toString() : "";

        // Đảm bảo chỉ một radio button trong nhóm trạng thái được chọn
        rdo_dadat.setSelected(false);  // Deselect tất cả trước
        rdo_trong.setSelected(false);
        if (trangThai.equalsIgnoreCase("Da dat")) {
            rdo_dadat.setSelected(true);
        } else if (trangThai.equalsIgnoreCase("Trong")) {
            rdo_trong.setSelected(true);
        }

        // Đảm bảo chỉ một radio button trong nhóm loại phòng được chọn
        rdo_vip.setSelected(false);  // Deselect tất cả trước
        rdo_thuong.setSelected(false);
        if (loaiPhong.equalsIgnoreCase("Vip")) {
            rdo_vip.setSelected(true);
        } else if (loaiPhong.equalsIgnoreCase("Thuong")) {
            rdo_thuong.setSelected(true);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Loi khi hien thi du lieu");
    }
}


    public Model_Phong readForm() {
        String id_phong;
        boolean loai_phong;
        String gia_phong;
        String tang;
        float dientich;
        String ghichu;
        boolean trangthai;

        // Kiểm tra ID phòng
        if (txt_id_Phong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID phong trong");
            txt_id_Phong.requestFocus();
            return null;
        }
        id_phong = txt_id_Phong.getText().trim();

        // Kiểm tra giá phòng
        if (txt_gia_Phong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Gia phong trong");
            txt_gia_Phong.requestFocus();
            return null;
        }
        gia_phong = txt_gia_Phong.getText().trim();

        // Kiểm tra loại phòng (VIP hoặc thường)
        loai_phong = rdo_vip.isSelected();

        // Kiểm tra trạng thái phòng (Đã đặt hoặc Trống)
        trangthai = rdo_dadat.isSelected();

        return new Model_Phong(id_phong, loai_phong, dientich, tang, WIDTH, ghichu, trangthai);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_id_Phong = new javax.swing.JTextField();
        txt_gia_Phong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        rdo_trong = new javax.swing.JRadioButton();
        rdo_dadat = new javax.swing.JRadioButton();
        rdo_vip = new javax.swing.JRadioButton();
        rdo_thuong = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã Phòng");

        jLabel2.setText("Giá Phòng");

        jLabel3.setText("jLabel3");

        jLabel4.setText("Trạng Thái");

        txt_gia_Phong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gia_PhongActionPerformed(evt);
            }
        });

        tbl_bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Phòng", "Loại Phòng", "Giá Phòng", "Tầng", "Diện tích", "Ghi Chú", "Trạng Thái"
            }
        ));
        tbl_bang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_bang);

        jLabel5.setText("Loại Phòng");

        buttonGroup2.add(rdo_trong);
        rdo_trong.setSelected(true);
        rdo_trong.setText("Trống");

        buttonGroup2.add(rdo_dadat);
        rdo_dadat.setText("Đã Đặt");

        buttonGroup1.add(rdo_vip);
        rdo_vip.setSelected(true);
        rdo_vip.setText("Vip");

        buttonGroup1.add(rdo_thuong);
        rdo_thuong.setText("Thường");
        rdo_thuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_thuongActionPerformed(evt);
            }
        });

        jButton1.setText("Đặt Phòng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_gia_Phong, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(txt_id_Phong))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdo_vip)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdo_thuong))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdo_trong)
                                        .addGap(34, 34, 34)
                                        .addComponent(rdo_dadat))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_Phong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdo_vip)
                    .addComponent(rdo_thuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_gia_Phong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdo_trong)
                            .addComponent(rdo_dadat))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_thuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_thuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_thuongActionPerformed

    private void txt_gia_PhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gia_PhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gia_PhongActionPerformed

    private void tbl_bangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bangMouseClicked
        // TODO add your handling code here: index = tbl_bang.getSelectedRow();
          index = tbl_bang.getSelectedRow();
        this.showData(index);
    }//GEN-LAST:event_tbl_bangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Phong1_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Phong1_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Phong1_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Phong1_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Phong1_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdo_dadat;
    private javax.swing.JRadioButton rdo_thuong;
    private javax.swing.JRadioButton rdo_trong;
    private javax.swing.JRadioButton rdo_vip;
    private javax.swing.JTable tbl_bang;
    private javax.swing.JTextField txt_gia_Phong;
    private javax.swing.JTextField txt_id_Phong;
    // End of variables declaration//GEN-END:variables
}
